#!/usr/bin/env bash
# install and setup nginx web server
sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html

# permanently redirects traffic from /redirect_me to anther url
# and displays a custom 404 page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Configure Nginx so that its HTTP response contains a custom header
#       The name of the custom HTTP header must be X-Served-By
#       The value of the custom HTTP header must be the hostname of the server Nginx is running on

CONFIG="\\\n\tadd_header X-Served-By '$(hostname)';"
sudo sed -i "24i $CONFIG" /etc/nginx/sites-enabled/default

sudo service nginx start
